 spring:
   activemq:
     broker-url: tcp://localhost:61616?wireFormat.maxInactivityDuration=0
     user: admin
     password: admin
     pool:
       configuration:
         max-connections: 22
 server:
   port: 8080



